disabled_rules:
  - colon
  - comma
  - trailing_comma
  - control_statement
  - switch_case_alignment
  - nesting
  - multiple_closures_with_trailing_closure
  - function_parameter_count
opt_in_rules:
  - empty_count
included:
  - Sources
  - Tests
excluded:
  - DerivedData
  - fastlane
analyzer_rules:
  - explicit_self
force_cast: warning
force_try:
  severity: warning
line_length: 180
type_body_length:
  - 300
  - 400
file_length:
  warning: 400
  error: 600
function_body_length:
  warning: 50
  error: 60
type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80
  excluded: iPhone
  allowed_symbols: ["_"]
  excluded:
    - id
    - Id
    - vm
    - vc
    - AB
    - AM
    - BC
    - BM
identifier_name:
  allowed_symbols: ["_"]
  min_length:
    error: 3
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - Id
    - db
    - up
    - vm
    - vc
    - to
    - at
    - in
    - go
    - ko
    - AB
    - AM
    - BC
    - BM
    - ok
    - no
reporter: "xcode"
