name: Build & Deploy Documentation
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Build & Deploy Documentation
    runs-on: macos-11
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.2.1
            
    - name: Build Documentation
      run: xcodebuild docbuild -scheme RetroSwift -derivedDataPath ./docbuild -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 mini'

    - run: cp -R ./docbuild/Build/Products/Debug-iphonesimulator/RetroSwift.doccarchive/* ./docs/
    - run: cp ./docs/index.html ./docs/404.html

    - name: Commit files
      run: |
        git add ./docs
        git commit -m "Build Documentation 🚀" -a

    - name: Push changes
      uses: ad-m/github-push-action@master